### ISSUE TITLE
Snapping doesn't work with Qt.FramelessWindowHint on Windows

### ISSUE THREAD

**Issue by adamsiembida** [johanhelsing/qt-csd-demo#11]
I was testing the web browser demo in this project, and it seems that snapping is broken. Both dragging and resizing work fine. Turning off Qt.FramelessWindowHint fixes this problem, but obviously then title bar is back.

I'm not sure if this is a Windows-specific issue, but I am using Windows 10.

[Edit] I should have searched through the bug tracker, because it seems that this is a [known issue](https://bugreports.qt.io/browse/QTBUG-84466).

**Comment by johanhelsing** [comment]
Interesting, I didn't know when I implemented it. I didn't have windows at the time, so had to quickly borrow a coworkers machine to test that the code I'd written worked. I probably didn't try to snap there.

There is a WIP patch for it it seems, but seems like activity stalled: https://codereview.qt-project.org/c/qt/qtbase/+/325649

**Comment by trin94** [comment]
It seems like this is going to be fixed in `6.2.5` onwards: https://bugreports.qt.io/browse/QTBUG-84466

**Comment by johanhelsing** [comment]
Thanks. Qt 6.3.0 is released and has the fix. I think 6.2.5 (LTS) should be right around the corner as well, closing.
