### ISSUE TITLE
Client side decoration broken on Linux since 6.1.1

### ISSUE THREAD

**Issue by gmarull** [johanhelsing/qt-csd-demo#12]
Ref. https://bugreports.qt.io/browse/QTBUG-99652

**Comment by trin94** [comment]
I just tested it in a private project which uses PySide 6.2.4 and it works

**Comment by johanhelsing** [comment]
As far as I understand from the linked issue, it looks like this is/was an issue with qml drag and drop not working on linux on some qt versions.

Assuming this is fixed in Qt now.
