### ISSUE TITLE
Invalid edges QFlagsQt::Edge() passed to QWindow::startSystemResize, ignoring.

### ISSUE THREAD

**Issue by ToxicDragon** [johanhelsing/qt-csd-demo#5]
Using Qt 5.15 Alpha, I get the following errors when trying to move / resize the window (at least on wayland)

> qml webbrowser.qml
> Try resizing / moving of the window

`qml webbrowser.qml 
file:///home/christian/repos/qt-csd-demo/webbrowser.qml:72: TypeError: Property 'startSystemMove' of object QQuickWindowQmlImpl_QML_12(0x7f82c0006b50) is not a function
file:///home/christian/repos/qt-csd-demo/webbrowser.qml:54: TypeError: Property 'startSystemResize' of object QQuickWindowQmlImpl_QML_12(0x7f82c0006b50) is not a function
file:///home/christian/repos/qt-csd-demo/webbrowser.qml:54: TypeError: Property 'startSystemResize' of object QQuickWindowQmlImpl_QML_12(0x7f82c0006b50) is not a function
file:///home/christian/repos/qt-csd-demo/webbrowser.qml:54: TypeError: Type error
file:///home/christian/repos/qt-csd-demo/webbrowser.qml:72: TypeError: Property 'startSystemMove' of object QQuickWindowQmlImpl_QML_12(0x7f82c0006b50) is not a function
file:///home/christian/repos/qt-csd-demo/webbrowser.qml:72: TypeError: Type error`

**Comment by ToxicDragon** [comment]
Can confirm that the problem also occurs on X11

**Comment by ToxicDragon** [comment]
This big seems to be tracked at Qt: https://bugreports.qt.io/browse/QTBUG-82191

**Comment by ToxicDragon** [comment]
Alright, my mistake. I accidently tested using Qt 5.14 (old path still set). When using 5.15 the problems were gone. However, I found another problem: When resizing on the window's edges (not the corners), the following error messages appeared (for all 4 edges):

> Invalid edges QFlags<Qt::Edge>() passed to QWindow::startSystemResize, ignoring.
> 
> Invalid edges QFlags<Qt::Edge>() passed to QWindow::startSystemResize, ignoring.
> 
> Invalid edges QFlags<Qt::Edge>() passed to QWindow::startSystemResize, ignoring.
> 
> Invalid edges QFlags<Qt::Edge>() passed to QWindow::startSystemResize, ignoring.
> 

so resizing was only possible using the window's corners. Moving worked flawlessly.

**Comment by johanhelsing** [comment]
That's weird... Could you please print out the value of edges being sent to the startSystemResize?

**Comment by johanhelsing** [comment]
Turned out to be a windows specific bug. See upstream bug report linked above for details
